env: test
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gliiii/config.git
          username: gliiii
          password: Ligen199316
          basedir: D:\IntelliJ IDEA 2019.2\IdeaProjects\SpringCloud_Shell\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
